language: cpp
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq libqt4-dev qt4-dev-tools g++-4.8 libfftw3-dev libsndfile-dev
script: sh -c "mkdir _build; cd _build; qmake QMAKE_CXX=g++-4.8 ../src/lib_testapp/lib_testapp.pro && make; cd ../output; ./lib_testapp"
